### PR TITLE
:bug: fix: fix page

### LINKED ISSUE #157: [BUG] 分页无效
**Describe the bug**
前端页码参数为current,后端页码参数为page,导致分页无效

**To Reproduce**
分页无效

**Expected behavior**

**Screenshots**
image
image

**Desktop (please complete the following information):**
- OS: [e.g., Windows 10]
- Browser: [e.g., Chrome, Safari]
- Version: [e.g., 22]

**Smartphone (please complete the following information):**
- Device: [e.g., iPhone X]
- OS: [e.g., iOS 14.4]
- Browser: [e.g., stock browser, Safari]
- Version: [e.g., 22]

**Additional context**

### PR DESCRIPTION
**Pull request by wxip**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #157 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: apis/department.go [hunk 1]
```diff
@@ -2,6 +2,7 @@ package apis
 
 import (
 	"fmt"
+	"gorm.io/gorm"
```
Comment (lwnmengjing) [inline apis/department.go:5]: 使用三段式import格式，
内置包

三方包

本项目包

Comment (wxip) [reply apis/department.go]: fix

**Review by lwnmengjing — APPROVED** [review]
